name: xpublish
channels:
  - conda-forge
dependencies:
  - python=3.10
  - git
  - xarray
  - netCDF4
  - xpublish
  - zarr
  - dask
  - distributed
  - shapely
  - cf_xarray
  - pydantic
  - httpx
  - sentry-sdk
  - pip:
      - git+https://github.com/gulfofmaine/xpublish-edr.git@454fed1aa4fbb33db194357e9b61f295d087c623
